### ISSUE TITLE
Créer un fichier Maxime.txt

### ISSUE THREAD

**Issue by mbrehin** [mbrehin/mint-git#1]
Créer à la racine du projet un fichier **Maxime.txt**

**Comment by mbrehin** [comment]
ça va ou bien ?

@jalleron @waldodev  qu'en pensez-vous ?

**Comment by EConnan** [comment]
Bof (Je reste dans mon rôle de râleur)

**Comment by jalleron** [comment]
Bien merci et toi ?

------ Message d'origine ------
De: "Maxime Bréhin" ***@***.***>
À: "mbrehin/mint-git" ***@***.***>
Cc : "jalleron" ***@***.***>; "Mention" 
***@***.***>
Envoyé : 10/06/2021 16:13:05
Objet : Re: [mbrehin/mint-git] Créer un fichier Maxime.txt (#1)

>
>ça va ou bien ?
>
***@***.*** ***@***.***
